title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

search_enabled: true
search.heading_level: 2
search.previews: 3
search.preview_words_before: 5
search.preview_words_after: 5
search.tokenizer_separator: /[\s/]+/
search.rel_url: false
search.button: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
